# Generated by Django 4.1.5 on 2023-03-07 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applianceType', models.CharField(max_length=11)),
                ('name', models.CharField(default='Other', max_length=100)),
                ('wattage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnergyProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Other', max_length=100, unique=True)),
                ('elecDailyCharge', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('gasDailyCharge', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('elecPerKwh', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('gasPerKwh', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('dob', models.DateField()),
                ('provider', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='EnergyApp.energyprovider')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnergyApp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnergyApp.userprofile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='EnergyApp.forumpost')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('dailyElecCostBudget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weeklyElecCostBudget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthlyElecCostBudget', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dailyGasCostBudget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weeklyGasCostBudget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthlyGasCostBudget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnergyApp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnergyApp.appliance')),
            ],
        ),
        migrations.AddField(
            model_name='appliance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnergyApp.userprofile'),
        ),
    ]
